services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8000:8000"

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://shop_user:shop_password@postgres:5432/shop

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8002:8000"
    environment:
      PRODUCT_SERVICE_URL: http://product-service:8000
    depends_on:
      - product-service
  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: shop_user
      POSTGRES_PASSWORD: shop_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U shop_user -d shop" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
